# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule PgQuery.NullTestType do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :NULL_TEST_TYPE_UNDEFINED
    def default() do
      :NULL_TEST_TYPE_UNDEFINED
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:NULL_TEST_TYPE_UNDEFINED) do
    0
  end

  def encode(:IS_NULL) do
    1
  end

  def encode(:IS_NOT_NULL) do
    2
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :NULL_TEST_TYPE_UNDEFINED
  end

  def decode(1) do
    :IS_NULL
  end

  def decode(2) do
    :IS_NOT_NULL
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [{0, :NULL_TEST_TYPE_UNDEFINED}, {1, :IS_NULL}, {2, :IS_NOT_NULL}]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:NULL_TEST_TYPE_UNDEFINED) do
      true
    end

    def has_constant?(:IS_NULL) do
      true
    end

    def has_constant?(:IS_NOT_NULL) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
