# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule PgQuery.RoleStmtType do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :ROLE_STMT_TYPE_UNDEFINED
    def default() do
      :ROLE_STMT_TYPE_UNDEFINED
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:ROLE_STMT_TYPE_UNDEFINED) do
    0
  end

  def encode(:ROLESTMT_ROLE) do
    1
  end

  def encode(:ROLESTMT_USER) do
    2
  end

  def encode(:ROLESTMT_GROUP) do
    3
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :ROLE_STMT_TYPE_UNDEFINED
  end

  def decode(1) do
    :ROLESTMT_ROLE
  end

  def decode(2) do
    :ROLESTMT_USER
  end

  def decode(3) do
    :ROLESTMT_GROUP
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [
      {0, :ROLE_STMT_TYPE_UNDEFINED},
      {1, :ROLESTMT_ROLE},
      {2, :ROLESTMT_USER},
      {3, :ROLESTMT_GROUP}
    ]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:ROLE_STMT_TYPE_UNDEFINED) do
      true
    end

    def has_constant?(:ROLESTMT_ROLE) do
      true
    end

    def has_constant?(:ROLESTMT_USER) do
      true
    end

    def has_constant?(:ROLESTMT_GROUP) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
