# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule PgQuery.PublicationObjSpecType do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :PUBLICATION_OBJ_SPEC_TYPE_UNDEFINED
    def default() do
      :PUBLICATION_OBJ_SPEC_TYPE_UNDEFINED
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:PUBLICATION_OBJ_SPEC_TYPE_UNDEFINED) do
    0
  end

  def encode(:PUBLICATIONOBJ_TABLE) do
    1
  end

  def encode(:PUBLICATIONOBJ_TABLES_IN_SCHEMA) do
    2
  end

  def encode(:PUBLICATIONOBJ_TABLES_IN_CUR_SCHEMA) do
    3
  end

  def encode(:PUBLICATIONOBJ_CONTINUATION) do
    4
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :PUBLICATION_OBJ_SPEC_TYPE_UNDEFINED
  end

  def decode(1) do
    :PUBLICATIONOBJ_TABLE
  end

  def decode(2) do
    :PUBLICATIONOBJ_TABLES_IN_SCHEMA
  end

  def decode(3) do
    :PUBLICATIONOBJ_TABLES_IN_CUR_SCHEMA
  end

  def decode(4) do
    :PUBLICATIONOBJ_CONTINUATION
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [
      {0, :PUBLICATION_OBJ_SPEC_TYPE_UNDEFINED},
      {1, :PUBLICATIONOBJ_TABLE},
      {2, :PUBLICATIONOBJ_TABLES_IN_SCHEMA},
      {3, :PUBLICATIONOBJ_TABLES_IN_CUR_SCHEMA},
      {4, :PUBLICATIONOBJ_CONTINUATION}
    ]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:PUBLICATION_OBJ_SPEC_TYPE_UNDEFINED) do
      true
    end

    def has_constant?(:PUBLICATIONOBJ_TABLE) do
      true
    end

    def has_constant?(:PUBLICATIONOBJ_TABLES_IN_SCHEMA) do
      true
    end

    def has_constant?(:PUBLICATIONOBJ_TABLES_IN_CUR_SCHEMA) do
      true
    end

    def has_constant?(:PUBLICATIONOBJ_CONTINUATION) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
