# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule PgQuery.JsonExprOp do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :JSON_EXPR_OP_UNDEFINED
    def default() do
      :JSON_EXPR_OP_UNDEFINED
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:JSON_EXPR_OP_UNDEFINED) do
    0
  end

  def encode(:JSON_EXISTS_OP) do
    1
  end

  def encode(:JSON_QUERY_OP) do
    2
  end

  def encode(:JSON_VALUE_OP) do
    3
  end

  def encode(:JSON_TABLE_OP) do
    4
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :JSON_EXPR_OP_UNDEFINED
  end

  def decode(1) do
    :JSON_EXISTS_OP
  end

  def decode(2) do
    :JSON_QUERY_OP
  end

  def decode(3) do
    :JSON_VALUE_OP
  end

  def decode(4) do
    :JSON_TABLE_OP
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [
      {0, :JSON_EXPR_OP_UNDEFINED},
      {1, :JSON_EXISTS_OP},
      {2, :JSON_QUERY_OP},
      {3, :JSON_VALUE_OP},
      {4, :JSON_TABLE_OP}
    ]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:JSON_EXPR_OP_UNDEFINED) do
      true
    end

    def has_constant?(:JSON_EXISTS_OP) do
      true
    end

    def has_constant?(:JSON_QUERY_OP) do
      true
    end

    def has_constant?(:JSON_VALUE_OP) do
      true
    end

    def has_constant?(:JSON_TABLE_OP) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
