# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule PgQuery.ImportForeignSchemaType do
  @moduledoc false
  @type t :: %__MODULE__{}
  defstruct []

  (
    @spec default() :: :IMPORT_FOREIGN_SCHEMA_TYPE_UNDEFINED
    def default() do
      :IMPORT_FOREIGN_SCHEMA_TYPE_UNDEFINED
    end
  )

  @spec encode(atom() | String.t()) :: integer() | atom()
  def encode(:IMPORT_FOREIGN_SCHEMA_TYPE_UNDEFINED) do
    0
  end

  def encode(:FDW_IMPORT_SCHEMA_ALL) do
    1
  end

  def encode(:FDW_IMPORT_SCHEMA_LIMIT_TO) do
    2
  end

  def encode(:FDW_IMPORT_SCHEMA_EXCEPT) do
    3
  end

  def encode(x) do
    x
  end

  @spec decode(integer()) :: atom() | integer()
  def decode(0) do
    :IMPORT_FOREIGN_SCHEMA_TYPE_UNDEFINED
  end

  def decode(1) do
    :FDW_IMPORT_SCHEMA_ALL
  end

  def decode(2) do
    :FDW_IMPORT_SCHEMA_LIMIT_TO
  end

  def decode(3) do
    :FDW_IMPORT_SCHEMA_EXCEPT
  end

  def decode(x) do
    x
  end

  @spec constants() :: [{integer(), atom()}]
  def constants() do
    [
      {0, :IMPORT_FOREIGN_SCHEMA_TYPE_UNDEFINED},
      {1, :FDW_IMPORT_SCHEMA_ALL},
      {2, :FDW_IMPORT_SCHEMA_LIMIT_TO},
      {3, :FDW_IMPORT_SCHEMA_EXCEPT}
    ]
  end

  @spec has_constant?(any()) :: boolean()
  (
    def has_constant?(:IMPORT_FOREIGN_SCHEMA_TYPE_UNDEFINED) do
      true
    end

    def has_constant?(:FDW_IMPORT_SCHEMA_ALL) do
      true
    end

    def has_constant?(:FDW_IMPORT_SCHEMA_LIMIT_TO) do
      true
    end

    def has_constant?(:FDW_IMPORT_SCHEMA_EXCEPT) do
      true
    end

    def has_constant?(_) do
      false
    end
  )
end
