# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule PgQuery.JsonExpr do
  @moduledoc false
  if function_exported?(Protox, :check_generator_version, 1) do
    Protox.check_generator_version(1)
  else
    raise "This code was generated with protox 2 but the runtime is using an older version of protox."
  end

  @type t :: %__MODULE__{
          location: integer(),
          collation: non_neg_integer(),
          omit_quotes: boolean(),
          wrapper: atom(),
          use_json_coercion: boolean(),
          use_io_coercion: boolean(),
          on_error: PgQuery.JsonBehavior.t() | nil,
          on_empty: PgQuery.JsonBehavior.t() | nil,
          passing_values: [PgQuery.Node.t()],
          passing_names: [PgQuery.Node.t()],
          returning: PgQuery.JsonReturning.t() | nil,
          path_spec: PgQuery.Node.t() | nil,
          format: PgQuery.JsonFormat.t() | nil,
          formatted_expr: PgQuery.Node.t() | nil,
          column_name: String.t(),
          op: atom(),
          xpr: PgQuery.Node.t() | nil,
          __uf__: [{non_neg_integer(), Protox.Types.tag(), binary()}]
        }
  defstruct location: 0,
            collation: 0,
            omit_quotes: false,
            wrapper: :JSON_WRAPPER_UNDEFINED,
            use_json_coercion: false,
            use_io_coercion: false,
            on_error: nil,
            on_empty: nil,
            passing_values: [],
            passing_names: [],
            returning: nil,
            path_spec: nil,
            format: nil,
            formatted_expr: nil,
            column_name: "",
            op: :JSON_EXPR_OP_UNDEFINED,
            xpr: nil,
            __uf__: []

  (
    (
      @spec encode(t()) :: {:ok, iodata(), non_neg_integer()} | {:error, any()}
      def encode(msg) do
        msg |> encode!() |> Tuple.insert_at(0, :ok)
      rescue
        e in [Protox.EncodingError, Protox.RequiredFieldsError] -> {:error, e}
      end

      @spec encode!(t()) :: {iodata(), non_neg_integer()} | no_return()
      def encode!(msg) do
        {_acc = [], _acc_size = 0}
        |> encode_location(msg)
        |> encode_collation(msg)
        |> encode_omit_quotes(msg)
        |> encode_wrapper(msg)
        |> encode_use_json_coercion(msg)
        |> encode_use_io_coercion(msg)
        |> encode_on_error(msg)
        |> encode_on_empty(msg)
        |> encode_passing_values(msg)
        |> encode_passing_names(msg)
        |> encode_returning(msg)
        |> encode_path_spec(msg)
        |> encode_format(msg)
        |> encode_formatted_expr(msg)
        |> encode_column_name(msg)
        |> encode_op(msg)
        |> encode_xpr(msg)
        |> encode_unknown_fields(msg)
      end
    )

    defp encode_location({acc, acc_size}, msg) do
      if msg.location == 0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_int32(msg.location)
        {["\x88\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:location, "invalid field value"), __STACKTRACE__
    end

    defp encode_collation({acc, acc_size}, msg) do
      if msg.collation == 0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_uint32(msg.collation)
        {["\x80\x01", value_bytes | acc], acc_size + 2 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:collation, "invalid field value"), __STACKTRACE__
    end

    defp encode_omit_quotes({acc, acc_size}, msg) do
      if msg.omit_quotes == false do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_bool(msg.omit_quotes)
        {["x", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:omit_quotes, "invalid field value"), __STACKTRACE__
    end

    defp encode_wrapper({acc, acc_size}, msg) do
      if msg.wrapper == :JSON_WRAPPER_UNDEFINED do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} =
          msg.wrapper |> PgQuery.JsonWrapper.encode() |> Protox.Encode.encode_enum()

        {["p", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:wrapper, "invalid field value"), __STACKTRACE__
    end

    defp encode_use_json_coercion({acc, acc_size}, msg) do
      if msg.use_json_coercion == false do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_bool(msg.use_json_coercion)
        {["h", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:use_json_coercion, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_use_io_coercion({acc, acc_size}, msg) do
      if msg.use_io_coercion == false do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_bool(msg.use_io_coercion)
        {["`", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:use_io_coercion, "invalid field value"), __STACKTRACE__
    end

    defp encode_on_error({acc, acc_size}, msg) do
      if msg.on_error == nil do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_message(msg.on_error)
        {["Z", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:on_error, "invalid field value"), __STACKTRACE__
    end

    defp encode_on_empty({acc, acc_size}, msg) do
      if msg.on_empty == nil do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_message(msg.on_empty)
        {["R", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:on_empty, "invalid field value"), __STACKTRACE__
    end

    defp encode_passing_values({acc, acc_size}, msg) do
      case msg.passing_values do
        [] ->
          {acc, acc_size}

        values ->
          {value_bytes, value_size} =
            (
              {value_bytes, value_size} =
                Enum.reduce(values, {_local_acc = [], _local_acc_size = 0}, fn value,
                                                                               {local_acc,
                                                                                local_acc_size} ->
                  {value_bytes, value_bytes_size} = Protox.Encode.encode_message(value)
                  {[value_bytes, "J" | local_acc], local_acc_size + 1 + value_bytes_size}
                end)

              {Enum.reverse(value_bytes), value_size}
            )

          {[value_bytes | acc], acc_size + value_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:passing_values, "invalid field value"), __STACKTRACE__
    end

    defp encode_passing_names({acc, acc_size}, msg) do
      case msg.passing_names do
        [] ->
          {acc, acc_size}

        values ->
          {value_bytes, value_size} =
            (
              {value_bytes, value_size} =
                Enum.reduce(values, {_local_acc = [], _local_acc_size = 0}, fn value,
                                                                               {local_acc,
                                                                                local_acc_size} ->
                  {value_bytes, value_bytes_size} = Protox.Encode.encode_message(value)
                  {[value_bytes, "B" | local_acc], local_acc_size + 1 + value_bytes_size}
                end)

              {Enum.reverse(value_bytes), value_size}
            )

          {[value_bytes | acc], acc_size + value_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:passing_names, "invalid field value"), __STACKTRACE__
    end

    defp encode_returning({acc, acc_size}, msg) do
      if msg.returning == nil do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_message(msg.returning)
        {[":", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:returning, "invalid field value"), __STACKTRACE__
    end

    defp encode_path_spec({acc, acc_size}, msg) do
      if msg.path_spec == nil do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_message(msg.path_spec)
        {["2", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:path_spec, "invalid field value"), __STACKTRACE__
    end

    defp encode_format({acc, acc_size}, msg) do
      if msg.format == nil do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_message(msg.format)
        {["*", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:format, "invalid field value"), __STACKTRACE__
    end

    defp encode_formatted_expr({acc, acc_size}, msg) do
      if msg.formatted_expr == nil do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_message(msg.formatted_expr)
        {["\"", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:formatted_expr, "invalid field value"), __STACKTRACE__
    end

    defp encode_column_name({acc, acc_size}, msg) do
      if msg.column_name == "" do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_string(msg.column_name)
        {["\x1A", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:column_name, "invalid field value"), __STACKTRACE__
    end

    defp encode_op({acc, acc_size}, msg) do
      if msg.op == :JSON_EXPR_OP_UNDEFINED do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} =
          msg.op |> PgQuery.JsonExprOp.encode() |> Protox.Encode.encode_enum()

        {["\x10", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:op, "invalid field value"), __STACKTRACE__
    end

    defp encode_xpr({acc, acc_size}, msg) do
      if msg.xpr == nil do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_message(msg.xpr)
        {["\n", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:xpr, "invalid field value"), __STACKTRACE__
    end

    defp encode_unknown_fields({acc, acc_size}, msg) do
      Enum.reduce(msg.__uf__, {acc, acc_size}, fn {tag, wire_type, bytes}, {acc, acc_size} ->
        case wire_type do
          0 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :int32)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}

          1 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :double)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}

          2 ->
            {len_bytes, len_size} = bytes |> byte_size() |> Protox.Varint.encode()
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :packed)

            {[acc, <<key_bytes::binary, len_bytes::binary, bytes::binary>>],
             acc_size + key_size + len_size + byte_size(bytes)}

          5 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :float)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}
        end
      end)
    end
  )

  (
    (
      @spec decode(binary()) :: {:ok, t()} | {:error, any()}
      def decode(bytes) do
        {:ok, decode!(bytes)}
      rescue
        e in [Protox.DecodingError, Protox.IllegalTagError, Protox.RequiredFieldsError] ->
          {:error, e}
      end

      (
        @spec decode!(binary()) :: t() | no_return()
        def decode!(bytes) do
          parse_key_value(bytes, struct(PgQuery.JsonExpr))
        end
      )
    )

    (
      @spec parse_key_value(binary(), struct()) :: struct()
      defp parse_key_value(<<>>, msg) do
        msg
      end

      defp parse_key_value(bytes, msg) do
        {field, rest} =
          case bytes do
            <<_::5, 3::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 3")

            <<_::5, 4::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 4")

            <<_::5, 6::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 6")

            <<_::5, 7::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 7")

            <<0::5, _::3, _rest::binary>> ->
              raise %Protox.IllegalTagError{}

            <<17::5, _wire_type::3, "\x01", bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_int32(bytes)
              {[location: value], rest}

            <<16::5, _wire_type::3, "\x01", bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_uint32(bytes)
              {[collation: value], rest}

            <<15::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_bool(bytes)
              {[omit_quotes: value], rest}

            <<14::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_enum(bytes, PgQuery.JsonWrapper)
              {[wrapper: value], rest}

            <<13::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_bool(bytes)
              {[use_json_coercion: value], rest}

            <<12::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_bool(bytes)
              {[use_io_coercion: value], rest}

            <<11::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 on_error:
                   Protox.MergeMessage.merge(
                     msg.on_error,
                     PgQuery.JsonBehavior.decode!(delimited)
                   )
               ], rest}

            <<10::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 on_empty:
                   Protox.MergeMessage.merge(
                     msg.on_empty,
                     PgQuery.JsonBehavior.decode!(delimited)
                   )
               ], rest}

            <<9::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[passing_values: msg.passing_values ++ [PgQuery.Node.decode!(delimited)]], rest}

            <<8::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[passing_names: msg.passing_names ++ [PgQuery.Node.decode!(delimited)]], rest}

            <<7::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 returning:
                   Protox.MergeMessage.merge(
                     msg.returning,
                     PgQuery.JsonReturning.decode!(delimited)
                   )
               ], rest}

            <<6::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 path_spec:
                   Protox.MergeMessage.merge(msg.path_spec, PgQuery.Node.decode!(delimited))
               ], rest}

            <<5::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 format:
                   Protox.MergeMessage.merge(msg.format, PgQuery.JsonFormat.decode!(delimited))
               ], rest}

            <<4::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 formatted_expr:
                   Protox.MergeMessage.merge(msg.formatted_expr, PgQuery.Node.decode!(delimited))
               ], rest}

            <<3::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[column_name: Protox.Decode.validate_string!(delimited)], rest}

            <<2::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_enum(bytes, PgQuery.JsonExprOp)
              {[op: value], rest}

            <<1::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[xpr: Protox.MergeMessage.merge(msg.xpr, PgQuery.Node.decode!(delimited))], rest}

            <<bytes::binary>> ->
              {tag, wire_type, rest} = Protox.Decode.parse_key(bytes)
              {value, rest} = Protox.Decode.parse_unknown(tag, wire_type, rest)
              {[__uf__: msg.__uf__ ++ [value]], rest}
          end

        msg_updated = struct(msg, field)
        parse_key_value(rest, msg_updated)
      end
    )
  )

  (
    @spec unknown_fields(struct()) :: [{non_neg_integer(), Protox.Types.tag(), binary()}]
    def unknown_fields(msg) do
      msg.__uf__
    end

    @spec unknown_fields_name() :: :__uf__
    def unknown_fields_name() do
      :__uf__
    end

    @spec clear_unknown_fields(struct) :: struct
    def clear_unknown_fields(msg) do
      struct!(msg, __uf__: [])
    end
  )

  (
    @spec default(atom()) ::
            {:ok, boolean() | integer() | String.t() | float()}
            | {:error, :no_such_field | :no_default_value}
    def default(:location) do
      {:ok, 0}
    end

    def default(:collation) do
      {:ok, 0}
    end

    def default(:omit_quotes) do
      {:ok, false}
    end

    def default(:wrapper) do
      {:ok, :JSON_WRAPPER_UNDEFINED}
    end

    def default(:use_json_coercion) do
      {:ok, false}
    end

    def default(:use_io_coercion) do
      {:ok, false}
    end

    def default(:on_error) do
      {:ok, nil}
    end

    def default(:on_empty) do
      {:ok, nil}
    end

    def default(:passing_values) do
      {:error, :no_default_value}
    end

    def default(:passing_names) do
      {:error, :no_default_value}
    end

    def default(:returning) do
      {:ok, nil}
    end

    def default(:path_spec) do
      {:ok, nil}
    end

    def default(:format) do
      {:ok, nil}
    end

    def default(:formatted_expr) do
      {:ok, nil}
    end

    def default(:column_name) do
      {:ok, ""}
    end

    def default(:op) do
      {:ok, :JSON_EXPR_OP_UNDEFINED}
    end

    def default(:xpr) do
      {:ok, nil}
    end

    def default(_) do
      {:error, :no_such_field}
    end
  )

  @spec schema() :: Protox.MessageSchema.t()
  def schema() do
    %{
      __struct__: Protox.MessageSchema,
      fields: %{
        collation: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: 0},
          label: :optional,
          name: :collation,
          tag: 16,
          type: :uint32
        },
        column_name: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: ""},
          label: :optional,
          name: :column_name,
          tag: 3,
          type: :string
        },
        format: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: nil},
          label: :optional,
          name: :format,
          tag: 5,
          type: {:message, PgQuery.JsonFormat}
        },
        formatted_expr: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: nil},
          label: :optional,
          name: :formatted_expr,
          tag: 4,
          type: {:message, PgQuery.Node}
        },
        location: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: 0},
          label: :optional,
          name: :location,
          tag: 17,
          type: :int32
        },
        omit_quotes: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: false},
          label: :optional,
          name: :omit_quotes,
          tag: 15,
          type: :bool
        },
        on_empty: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: nil},
          label: :optional,
          name: :on_empty,
          tag: 10,
          type: {:message, PgQuery.JsonBehavior}
        },
        on_error: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: nil},
          label: :optional,
          name: :on_error,
          tag: 11,
          type: {:message, PgQuery.JsonBehavior}
        },
        op: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: :JSON_EXPR_OP_UNDEFINED},
          label: :optional,
          name: :op,
          tag: 2,
          type: {:enum, PgQuery.JsonExprOp}
        },
        passing_names: %{
          __struct__: Protox.Field,
          kind: :unpacked,
          label: :repeated,
          name: :passing_names,
          tag: 8,
          type: {:message, PgQuery.Node}
        },
        passing_values: %{
          __struct__: Protox.Field,
          kind: :unpacked,
          label: :repeated,
          name: :passing_values,
          tag: 9,
          type: {:message, PgQuery.Node}
        },
        path_spec: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: nil},
          label: :optional,
          name: :path_spec,
          tag: 6,
          type: {:message, PgQuery.Node}
        },
        returning: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: nil},
          label: :optional,
          name: :returning,
          tag: 7,
          type: {:message, PgQuery.JsonReturning}
        },
        use_io_coercion: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: false},
          label: :optional,
          name: :use_io_coercion,
          tag: 12,
          type: :bool
        },
        use_json_coercion: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: false},
          label: :optional,
          name: :use_json_coercion,
          tag: 13,
          type: :bool
        },
        wrapper: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: :JSON_WRAPPER_UNDEFINED},
          label: :optional,
          name: :wrapper,
          tag: 14,
          type: {:enum, PgQuery.JsonWrapper}
        },
        xpr: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: nil},
          label: :optional,
          name: :xpr,
          tag: 1,
          type: {:message, PgQuery.Node}
        }
      },
      file_options: nil,
      name: PgQuery.JsonExpr,
      syntax: :proto3
    }
  end
end
