# Code generated by protox. Don't edit.
# credo:disable-for-this-file
defmodule PgQuery.OnConflictExpr do
  @moduledoc false
  if function_exported?(Protox, :check_generator_version, 1) do
    Protox.check_generator_version(1)
  else
    raise "This code was generated with protox 2 but the runtime is using an older version of protox."
  end

  @type t :: %__MODULE__{
          excl_rel_tlist: [PgQuery.Node.t()],
          excl_rel_index: integer(),
          on_conflict_where: PgQuery.Node.t() | nil,
          on_conflict_set: [PgQuery.Node.t()],
          constraint: non_neg_integer(),
          arbiter_where: PgQuery.Node.t() | nil,
          arbiter_elems: [PgQuery.Node.t()],
          action: atom(),
          __uf__: [{non_neg_integer(), Protox.Types.tag(), binary()}]
        }
  defstruct excl_rel_tlist: [],
            excl_rel_index: 0,
            on_conflict_where: nil,
            on_conflict_set: [],
            constraint: 0,
            arbiter_where: nil,
            arbiter_elems: [],
            action: :ON_CONFLICT_ACTION_UNDEFINED,
            __uf__: []

  (
    (
      @spec encode(t()) :: {:ok, iodata(), non_neg_integer()} | {:error, any()}
      def encode(msg) do
        msg |> encode!() |> Tuple.insert_at(0, :ok)
      rescue
        e in [Protox.EncodingError, Protox.RequiredFieldsError] -> {:error, e}
      end

      @spec encode!(t()) :: {iodata(), non_neg_integer()} | no_return()
      def encode!(msg) do
        {_acc = [], _acc_size = 0}
        |> encode_excl_rel_tlist(msg)
        |> encode_excl_rel_index(msg)
        |> encode_on_conflict_where(msg)
        |> encode_on_conflict_set(msg)
        |> encode_constraint(msg)
        |> encode_arbiter_where(msg)
        |> encode_arbiter_elems(msg)
        |> encode_action(msg)
        |> encode_unknown_fields(msg)
      end
    )

    defp encode_excl_rel_tlist({acc, acc_size}, msg) do
      case msg.excl_rel_tlist do
        [] ->
          {acc, acc_size}

        values ->
          {value_bytes, value_size} =
            (
              {value_bytes, value_size} =
                Enum.reduce(values, {_local_acc = [], _local_acc_size = 0}, fn value,
                                                                               {local_acc,
                                                                                local_acc_size} ->
                  {value_bytes, value_bytes_size} = Protox.Encode.encode_message(value)
                  {[value_bytes, "B" | local_acc], local_acc_size + 1 + value_bytes_size}
                end)

              {Enum.reverse(value_bytes), value_size}
            )

          {[value_bytes | acc], acc_size + value_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:excl_rel_tlist, "invalid field value"), __STACKTRACE__
    end

    defp encode_excl_rel_index({acc, acc_size}, msg) do
      if msg.excl_rel_index == 0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_int32(msg.excl_rel_index)
        {["8", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:excl_rel_index, "invalid field value"), __STACKTRACE__
    end

    defp encode_on_conflict_where({acc, acc_size}, msg) do
      if msg.on_conflict_where == nil do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_message(msg.on_conflict_where)
        {["2", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:on_conflict_where, "invalid field value"),
                __STACKTRACE__
    end

    defp encode_on_conflict_set({acc, acc_size}, msg) do
      case msg.on_conflict_set do
        [] ->
          {acc, acc_size}

        values ->
          {value_bytes, value_size} =
            (
              {value_bytes, value_size} =
                Enum.reduce(values, {_local_acc = [], _local_acc_size = 0}, fn value,
                                                                               {local_acc,
                                                                                local_acc_size} ->
                  {value_bytes, value_bytes_size} = Protox.Encode.encode_message(value)
                  {[value_bytes, "*" | local_acc], local_acc_size + 1 + value_bytes_size}
                end)

              {Enum.reverse(value_bytes), value_size}
            )

          {[value_bytes | acc], acc_size + value_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:on_conflict_set, "invalid field value"), __STACKTRACE__
    end

    defp encode_constraint({acc, acc_size}, msg) do
      if msg.constraint == 0 do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_uint32(msg.constraint)
        {[" ", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:constraint, "invalid field value"), __STACKTRACE__
    end

    defp encode_arbiter_where({acc, acc_size}, msg) do
      if msg.arbiter_where == nil do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} = Protox.Encode.encode_message(msg.arbiter_where)
        {["\x1A", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:arbiter_where, "invalid field value"), __STACKTRACE__
    end

    defp encode_arbiter_elems({acc, acc_size}, msg) do
      case msg.arbiter_elems do
        [] ->
          {acc, acc_size}

        values ->
          {value_bytes, value_size} =
            (
              {value_bytes, value_size} =
                Enum.reduce(values, {_local_acc = [], _local_acc_size = 0}, fn value,
                                                                               {local_acc,
                                                                                local_acc_size} ->
                  {value_bytes, value_bytes_size} = Protox.Encode.encode_message(value)
                  {[value_bytes, "\x12" | local_acc], local_acc_size + 1 + value_bytes_size}
                end)

              {Enum.reverse(value_bytes), value_size}
            )

          {[value_bytes | acc], acc_size + value_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:arbiter_elems, "invalid field value"), __STACKTRACE__
    end

    defp encode_action({acc, acc_size}, msg) do
      if msg.action == :ON_CONFLICT_ACTION_UNDEFINED do
        {acc, acc_size}
      else
        {value_bytes, value_bytes_size} =
          msg.action |> PgQuery.OnConflictAction.encode() |> Protox.Encode.encode_enum()

        {["\b", value_bytes | acc], acc_size + 1 + value_bytes_size}
      end
    rescue
      ArgumentError ->
        reraise Protox.EncodingError.new(:action, "invalid field value"), __STACKTRACE__
    end

    defp encode_unknown_fields({acc, acc_size}, msg) do
      Enum.reduce(msg.__uf__, {acc, acc_size}, fn {tag, wire_type, bytes}, {acc, acc_size} ->
        case wire_type do
          0 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :int32)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}

          1 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :double)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}

          2 ->
            {len_bytes, len_size} = bytes |> byte_size() |> Protox.Varint.encode()
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :packed)

            {[acc, <<key_bytes::binary, len_bytes::binary, bytes::binary>>],
             acc_size + key_size + len_size + byte_size(bytes)}

          5 ->
            {key_bytes, key_size} = Protox.Encode.make_key_bytes(tag, :float)
            {[acc, <<key_bytes::binary, bytes::binary>>], acc_size + key_size + byte_size(bytes)}
        end
      end)
    end
  )

  (
    (
      @spec decode(binary()) :: {:ok, t()} | {:error, any()}
      def decode(bytes) do
        {:ok, decode!(bytes)}
      rescue
        e in [Protox.DecodingError, Protox.IllegalTagError, Protox.RequiredFieldsError] ->
          {:error, e}
      end

      (
        @spec decode!(binary()) :: t() | no_return()
        def decode!(bytes) do
          parse_key_value(bytes, struct(PgQuery.OnConflictExpr))
        end
      )
    )

    (
      @spec parse_key_value(binary(), struct()) :: struct()
      defp parse_key_value(<<>>, msg) do
        msg
      end

      defp parse_key_value(bytes, msg) do
        {field, rest} =
          case bytes do
            <<_::5, 3::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 3")

            <<_::5, 4::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 4")

            <<_::5, 6::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 6")

            <<_::5, 7::3, _rest::binary>> ->
              raise Protox.DecodingError.new(bytes, "invalid wire type 7")

            <<0::5, _::3, _rest::binary>> ->
              raise %Protox.IllegalTagError{}

            <<8::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[excl_rel_tlist: msg.excl_rel_tlist ++ [PgQuery.Node.decode!(delimited)]], rest}

            <<7::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_int32(bytes)
              {[excl_rel_index: value], rest}

            <<6::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 on_conflict_where:
                   Protox.MergeMessage.merge(
                     msg.on_conflict_where,
                     PgQuery.Node.decode!(delimited)
                   )
               ], rest}

            <<5::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[on_conflict_set: msg.on_conflict_set ++ [PgQuery.Node.decode!(delimited)]], rest}

            <<4::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_uint32(bytes)
              {[constraint: value], rest}

            <<3::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)

              {[
                 arbiter_where:
                   Protox.MergeMessage.merge(msg.arbiter_where, PgQuery.Node.decode!(delimited))
               ], rest}

            <<2::5, _wire_type::3, bytes::binary>> ->
              {len, bytes} = Protox.Varint.decode(bytes)
              {delimited, rest} = Protox.Decode.parse_delimited(bytes, len)
              {[arbiter_elems: msg.arbiter_elems ++ [PgQuery.Node.decode!(delimited)]], rest}

            <<1::5, _wire_type::3, bytes::binary>> ->
              {value, rest} = Protox.Decode.parse_enum(bytes, PgQuery.OnConflictAction)
              {[action: value], rest}

            <<bytes::binary>> ->
              {tag, wire_type, rest} = Protox.Decode.parse_key(bytes)
              {value, rest} = Protox.Decode.parse_unknown(tag, wire_type, rest)
              {[__uf__: msg.__uf__ ++ [value]], rest}
          end

        msg_updated = struct(msg, field)
        parse_key_value(rest, msg_updated)
      end
    )
  )

  (
    @spec unknown_fields(struct()) :: [{non_neg_integer(), Protox.Types.tag(), binary()}]
    def unknown_fields(msg) do
      msg.__uf__
    end

    @spec unknown_fields_name() :: :__uf__
    def unknown_fields_name() do
      :__uf__
    end

    @spec clear_unknown_fields(struct) :: struct
    def clear_unknown_fields(msg) do
      struct!(msg, __uf__: [])
    end
  )

  (
    @spec default(atom()) ::
            {:ok, boolean() | integer() | String.t() | float()}
            | {:error, :no_such_field | :no_default_value}
    def default(:excl_rel_tlist) do
      {:error, :no_default_value}
    end

    def default(:excl_rel_index) do
      {:ok, 0}
    end

    def default(:on_conflict_where) do
      {:ok, nil}
    end

    def default(:on_conflict_set) do
      {:error, :no_default_value}
    end

    def default(:constraint) do
      {:ok, 0}
    end

    def default(:arbiter_where) do
      {:ok, nil}
    end

    def default(:arbiter_elems) do
      {:error, :no_default_value}
    end

    def default(:action) do
      {:ok, :ON_CONFLICT_ACTION_UNDEFINED}
    end

    def default(_) do
      {:error, :no_such_field}
    end
  )

  @spec schema() :: Protox.MessageSchema.t()
  def schema() do
    %{
      __struct__: Protox.MessageSchema,
      fields: %{
        action: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: :ON_CONFLICT_ACTION_UNDEFINED},
          label: :optional,
          name: :action,
          tag: 1,
          type: {:enum, PgQuery.OnConflictAction}
        },
        arbiter_elems: %{
          __struct__: Protox.Field,
          kind: :unpacked,
          label: :repeated,
          name: :arbiter_elems,
          tag: 2,
          type: {:message, PgQuery.Node}
        },
        arbiter_where: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: nil},
          label: :optional,
          name: :arbiter_where,
          tag: 3,
          type: {:message, PgQuery.Node}
        },
        constraint: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: 0},
          label: :optional,
          name: :constraint,
          tag: 4,
          type: :uint32
        },
        excl_rel_index: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: 0},
          label: :optional,
          name: :excl_rel_index,
          tag: 7,
          type: :int32
        },
        excl_rel_tlist: %{
          __struct__: Protox.Field,
          kind: :unpacked,
          label: :repeated,
          name: :excl_rel_tlist,
          tag: 8,
          type: {:message, PgQuery.Node}
        },
        on_conflict_set: %{
          __struct__: Protox.Field,
          kind: :unpacked,
          label: :repeated,
          name: :on_conflict_set,
          tag: 5,
          type: {:message, PgQuery.Node}
        },
        on_conflict_where: %{
          __struct__: Protox.Field,
          kind: %{__struct__: Protox.Scalar, default_value: nil},
          label: :optional,
          name: :on_conflict_where,
          tag: 6,
          type: {:message, PgQuery.Node}
        }
      },
      file_options: nil,
      name: PgQuery.OnConflictExpr,
      syntax: :proto3
    }
  end
end
